home:
  uri: ^/$
  zone: Public
  controller: HomeController
  action: show
  params: []

blog:
  uri: ^/blog/?$
  zone: Public
  controller: BlogController
  action: show
  params: []

blog_single_post:
  uri: ^/blog/([0-9]+)/?$
  zone: Public
  controller: BlogController
  action: showPost
  params: [id]

logout:
  uri: ^/logout/?$
  zone: Public
  controller: AccountController
  action: logout
  params: []

login:
  uri: ^/login/?$
  zone: Public
  controller: AccountController
  action: login
  params: []

register:
  uri: ^/register/?$
  zone: Public
  controller: AccountController
  action: register
  params: []

admin:
  uri: ^/admin/?$
  zone: Admin
  controller: AdminController
  action: show
  params: []

profil:
  uri: ^/admin/profil/?$
  zone: Admin
  controller: ProfilController
  action: show
  params: []

posts_list:
  uri: ^/admin/blog/?$
  zone: Admin
  controller: BlogController
  action: show
  params: []

post_new:
  uri: ^/admin/blog/new/?$
  zone: Admin
  controller: BlogController
  action: newPost
  params: []

post_edit:
  uri: ^/admin/blog/edit/([0-9]+)/?$
  zone: Admin
  controller: BlogController
  action: editPost
  params: []